<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1610485874404" stop="1610485928431" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1610485911862" stop="1610485916800" status="passed">
            <name>TC_01_Navigate_To_Patient_LoginRegister</name>
            <description type="text">Navigate_To_Patient_LoginRegister </description>
            <steps/>
            <attachments>
                <attachment title="EzHomePage" source="e72dcd37-829f-495b-81b7-1ca19140a73f-attachment.png" type="image/png"/>
            </attachments>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.sailotech.ezscheduler.Testpages.Consumerlogintest"/>
                <label name="testMethod" value="TC_01_Navigate_To_Patient_LoginRegister"/>
                <label name="severity" value="normal"/>
                <label name="testId" value="TC_13"/>
                <label name="host" value="DESKTOP-A4GJKOM"/>
                <label name="thread" value="51788@DESKTOP-A4GJKOM.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1610485916849" stop="1610485918739" status="broken">
            <name>TC_02_PatientLogin</name>
            <description type="text">Navigate_To_PatientLogin</description>
            <failure>
                <message>POIXMLException: org.apache.xmlbeans.XmlException: error: Unexpected end of file after null</message>
                <stack-trace>org.apache.poi.POIXMLException: org.apache.xmlbeans.XmlException: error: Unexpected end of file after null&#13;
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:375)&#13;
	at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:166)&#13;
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.&lt;init&gt;(XSSFWorkbook.java:263)&#13;
	at com.sailotech.ezscheduler.Implpages.Consumerlogin.PatientLogin(Consumerlogin.java:67)&#13;
	at com.sailotech.ezscheduler.Testpages.Consumerlogintest.TC_02_PatientLogin(Consumerlogintest.java:54)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)&#13;
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)&#13;
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)&#13;
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)&#13;
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)&#13;
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)&#13;
	at org.testng.TestRunner.privateRun(TestRunner.java:648)&#13;
	at org.testng.TestRunner.run(TestRunner.java:505)&#13;
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)&#13;
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)&#13;
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)&#13;
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)&#13;
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)&#13;
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)&#13;
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)&#13;
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)&#13;
	at org.testng.TestNG.runSuites(TestNG.java:1049)&#13;
	at org.testng.TestNG.run(TestNG.java:1017)&#13;
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&#13;
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&#13;
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)&#13;
Caused by: org.apache.xmlbeans.XmlException: error: Unexpected end of file after null&#13;
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3511)&#13;
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1277)&#13;
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1264)&#13;
	at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)&#13;
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.WorkbookDocument$Factory.parse(Unknown Source)&#13;
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:314)&#13;
	... 29 more&#13;
Caused by: org.xml.sax.SAXParseException; systemId: file:; lineNumber: 1; columnNumber: 1; Unexpected end of file after null&#13;
	at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.reportFatalError(Piccolo.java:1038)&#13;
	at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.parse(Piccolo.java:723)&#13;
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3479)&#13;
	... 34 more&#13;
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.sailotech.ezscheduler.Testpages.Consumerlogintest"/>
                <label name="testMethod" value="TC_02_PatientLogin"/>
                <label name="severity" value="normal"/>
                <label name="testId" value="TC_14"/>
                <label name="host" value="DESKTOP-A4GJKOM"/>
                <label name="thread" value="51788@DESKTOP-A4GJKOM.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
